// import BodyComponent from "@/components/body/BodyComponent";
// import HeadComponent from "@/components/head/HeadComponent";
// import Body from "@/components/Body";
import Body from "@/components/body/Body";
import Footer from "@/components/footer/Footer";
import Intro from "@/components/Intro";
import Nav from "@/components/Nav";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agric Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-[#FFFEFB]">
        <Nav />
        <Intro />
        <Body />
        <Footer />
        {/* <div className="my-44"></div> */}
      </div>
    </>
  );
}
