import BodyComponent from "@/components/body/BodyComponent";
import HeadComponent from "@/components/head/HeadComponent";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agric Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <HeadComponent />
        <BodyComponent />
      </div>
    </>
  );
}
